#!/usr/bin/env python3
import sys

# function to write text to the file
def write_to_file(filename, string):

    try:
        with open(filename, "w") as file:
            file.write(string)
            return True
    except Exception as e:
        print(f"Error occured when writing to file {e}")
    return False

# function to remove lines
def remove_lines(string, start, end):

    new_string = ""
    line_no = 0
    for char in string:
        if char == "\n":
            line_no += 1
        if line_no < start - 1 or line_no > end - 1:
            new_string += char
    return new_string

# function to read the contents of a file
def read_file(filename):

    try:
        with open(filename, "r") as file:
            content = file.read()
    except Exception as e:
        print(f"Error while reading file {e}")
    return content

# main function
def main():

    if len(sys.argv) != 4:
        print("invalid argument")
        sys.exit(1)
    
    #get the filename start line and end line
    filename = sys.argv[1]
    start = int(sys.argv[2])
    end = int(sys.argv[3])

    if start > end:
        print("end line number should be greater than start line number")
        sys.exit(1)
    
    # read text from the file
    string = read_file(filename)
            
    # delete lines from the file
    new_string = remove_lines(string, start, end)
    
    # write the new text to file
    success = write_to_file(filename, new_string)
    if success:
        print(f"Deleted lines from {start} to {end}")

# start program
if __name__ == "__main__":
    
    main()